### ISSUE TITLE
prevents copying comments

### ISSUE THREAD

**Issue by Luckz** [nhabuiduc/TypescriptSyntaxPaste#1]
After installing this, I can't copy-paste (ctrl-c and ctrl-v) comments ("//qweqwe") in Typescript anymore, even within the same file. It works fine for code and comments, but comments alone cannot be pasted into Typescript.
Copying from Typescript works fine, only pasting is affected.

Pastable:

```
var itemList = $('#selectItem');
//var itemId = itemList.val();
```

Not pastable:

```
//var itemId = itemList.val();
```

**Comment by nhabuiduc** [comment]
The reason is because it's recognized as a correct C# syntax, which currently not support converting comments to Typescript. I've fixed it by checking if it only contains comment, it will not be converted.
