### ISSUE TITLE
Visual Studio 2017 Support

### ISSUE THREAD

**Issue by plaramee1** [nhabuiduc/TypescriptSyntaxPaste#10]
Well the title say it all !

**Comment by PavelA85** [comment]
Waiting for VS2017 support!

**Comment by nhabuiduc** [comment]
Just installed VS 2017 and working on it, and there is one problem (Community version), I can not format Typescript code (plugin use VS for formatting), do you guys have the same problem?

**Comment by nhabuiduc** [comment]
Supported, please check, if it's not working in VS 2017, please try to upgrade VS 2017 to latest version
