### ISSUE TITLE
Lowercase class or interface members

### ISSUE THREAD

**Issue by dasviridov** [nhabuiduc/TypescriptSyntaxPaste#2]
It would be nice to have ts class or interface members lover cased automatically. 

E.g.

``` C#
    public class ModelBase
    {
       public int Id { get; set; }

        public string Name { get; set; }
    }
```

to 

``` typescript
    export interface IModelBase {
        id: number;
        name: string;
    }
```

**Comment by nhabuiduc** [comment]
added an option to convert member name to camel case (Option: Convert members to camelcase) 8fe42e1f22ce9ed237002b681e062d4a30e1e037

**Comment by dasviridov** [comment]
Confirmed it works. Thank you!

Please make a new release and publish it to visualstudiogallery.
