### ISSUE TITLE
Add DateTimeOffset to Date conversion

### ISSUE THREAD

**Issue by dasviridov** [nhabuiduc/TypescriptSyntaxPaste#3]
Please add conversion of DateTimeOffset to Date.

**Comment by nhabuiduc** [comment]
Added feature to convert DateTimeOffset to Date, or add manually which name to be replace( commit 52cd3f26bf73e0994c45bb1cd19d9b5bc8780678 ). For example:

Type name: Foo
New Type name: Bar

it will try to find any where with type name Foo -> Bar.

**Comment by dasviridov** [comment]
Confirmed it works. Thank you!
