### ISSUE TITLE
Ability to add prefix to ts interface

### ISSUE THREAD

**Issue by dasviridov** [nhabuiduc/TypescriptSyntaxPaste#6]
If C# model class is mapped to ts interface it would be good to add "I" prefix as per interface naming convention.

So UserModel class converts to IUserModel ts interface.

**Comment by nhabuiduc** [comment]
Added option to add "I" prefix in Interface Declaration in commit 75917fbe1ddef5276c3de450c046d9eeef8ae87f

**Comment by dasviridov** [comment]
All works. Thank you!
