### ISSUE TITLE
Problem with "throw" statement

### ISSUE THREAD

**Issue by oliver-h** [nhabuiduc/TypescriptSyntaxPaste#7]
TypescriptSyntaxPaste: 1.2.1

The "anonymous" throw statement will cause TypescriptSyntaxPaste fail to convert code.

This code sample can be converted:
<code>
    public void Foo()
    {
        try
        { }
        catch (Exception ex)
        {
            throw ex;
        }
    }
</code>
This code sample will cause the whole conversion to fail:
<code>
    public void Foo()
    {
        try
        { }
        catch (Exception)
        {
            throw;
        }
    }
</code>

**Comment by nhabuiduc** [comment]
Fixed on commit 7cefb090c2394f7ad9ca2c652ddaa10d03c2d192.

It will handle 4 cases with:
catch(Exception ex) { throw ;}
catch(Exception ) { throw ;}
catch { throw ;}
catch(Exception ex) { throw ex;}

**Comment by oliver-h** [comment]
Great! Thx!
