### ISSUE TITLE
Adding ? to property

### ISSUE THREAD

**Issue by denimaaark** [nhabuiduc/TypescriptSyntaxPaste#8]
Please can You add ? to property on paste ?

var CustomerId: number -> CustomerId?: number !

Problem is that if You tray to use properties from interface they are undefined, and if we want to define them we apways muset define them in constructor, for classes that has 50 propertyes this is problem.

Thank You

**Comment by nhabuiduc** [comment]
Added in commit d873e4e9effb63fa3748987395fd9ba85df36a51 , which provide an option to convert with ? as optional properties/methods in interface

**Comment by denimaaark** [comment]
Great, thank You, this is very useful for spa typescript development :-)
