### ISSUE TITLE
optional interface members

### ISSUE THREAD

**Issue by abbasmhd** [nhabuiduc/TypescriptSyntaxPaste#9]
can you make the interface generate in typescript to have all its members marked as optional

```
export interface ILookup {
    description?: string; // notice the ? after the member name
}
```

**Comment by nhabuiduc** [comment]
I think I've already made it, is it the one you need? 

https://github.com/nhabuiduc/TypescriptSyntaxPaste/issues/8

**Comment by abbasmhd** [comment]
yes that's the one i need thanks you, but i cannot see it in the options dialog. i have version 1.2.1 installed

![image](https://cloud.githubusercontent.com/assets/1510389/19791580/a3e72f7e-9d05-11e6-9898-6517a579c69e.png)

**Comment by nhabuiduc** [comment]
I think something wrong with version showing in Vistual Studio Gallery now (it should be 1.2.4), for now, can you try download extension again, and try.

**Comment by nhabuiduc** [comment]
Hmm it's not in latest version, i will update it

**Comment by nhabuiduc** [comment]
Updated, please download again on Visualstudio Gallery

**Comment by abbasmhd** [comment]
thank you @nhabuiduc  works like a charm
